[devvy]
    volume = "0.15"
    [[devvy.trigger]]
        name = "biome"
        biome_category = "unknawon"
[leo]
    volume = "0.15"
    [[leo.trigger]]
        name = "acidrain"
[shack]
    volume = "0.15"
    [[shack.trigger]]
        name = "fallingstars"
[crackbox]
    volume = "0.15"
    [[crackbox.trigger]]
        name = "bloodmoon"
[goob]
    volume = "0.15"
    [[goob.trigger]]
        name = "advancement"
        time = "1"
        advancement = "IMPOSSIBLE ADVANCEMENT"
        identifier = "fart"
[skao]
    volume = "0.15"
    [[skao.trigger]]
        name = "blizzard"
[toby]
    volume = "0.15"
    [[toby.trigger]]
        name = "cloudy"
[triple]
    volume = "0.15"
    [[triple.trigger]]
        name = "rainintensity"
        level = "100"
        identifier = "pooooooo"

