[blackstar]
    volume = "0.10"
    [blackstar.trigger]
        name = "moon"
[dracontium]
    volume = "0.10"
    [dracontium.trigger]
        name = "bluemoon"
[foxontherun]
    volume = "0.10"
    [foxontherun.trigger]
        name = "fallingstars"
[invisibleman]
    volume = "0.10"
    [invisibleman.trigger]
        name = "bloodmoon"
[nikes]
    volume = "0.10"
    [nikes.trigger]
        name = "gamestage"
[softfuzzyman]
    volume = "0.10"
    [softfuzzyman.trigger]
        name = "blizzard"
[yousuck]
    volume = "0.10"
    [yousuck.trigger]
        name = "cloudy"
[bakamitai]
    volume = "0.10"
    [bakamitai.trigger]
        name = "lightrain"
