[blackstar]
    volume = "0.15"
    [[blackstar.trigger]]
        name = "biome"
        biome_category = "unknawon"
[dracontium]
    volume = "0.15"
    [[dracontium.trigger]]
        name = "acidrain"
[foxontherun]
    volume = "0.15"
    [[foxontherun.trigger]]
        name = "fallingstars"
[invisibleman]
    volume = "0.15"
    [[invisibleman.trigger]]
        name = "bloodmoon"
[nikes]
    volume = "0.15"
    [[nikes.trigger]]
        name = "gamestage"
[softfuzzyman]
    volume = "0.15"
    [[softfuzzyman.trigger]]
        name = "blizzard"
[yousuck]
    volume = "0.15"
    [[yousuck.trigger]]
        name = "cloudy"
[bakamitai]
    volume = "0.15"
    [[bakamitai.trigger]]
        name = "lightrain"
