
name: Zip Files

on: push

jobs:
  zip-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: papeloto/action-zip@v1
        with:
          files: /CFPbu/bin /CFPbu/configs /CFPbu/Flan /CFPbu/mods 
          dest: CFPbu.zip
      - uses: actions/upload-artifact@v1
        with:
          name: CFPbu.zip
          path: ${{ github.workspace }}/CFPbu.zip
      - uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Automatic release
          draft: false
          prerelease: true
