
name: Generate Modpack ZIP

on: push

jobs:
  zip-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: papeloto/action-zip@v1
        with:
          files: /CFPbu/bin /CFPbu/configs /CFPbu/Flan /CFPbu/mods 
          recursive: false
          dest: CFPbu.zip
      - uses: actions/upload-artifact@v1
        with:
          name: CFPbu.zip
          path: ${{ github.workspace }}/CFPbu.zip
      - name: Commit files
        run: |
          cd ${{ github.workspace }}
          git config --global user.email "actions@pnfx.dev"
          git config --global user.name "Pencil Fox"
          git add .
          git commit -a -m "Generated Modpack ZIP File, yip! [skip ci]"
          git push -u origin HEAD:main
  #    - name: Push changes
  #      uses: ad-m/github-push-action@master
  #      with:
  #        github_token: ${{ secrets.GITHUB_TOKEN }}
  #        branch: ${{ github.ref }}
  #       - uses: actions/create-release@v1
  #         env:
  #           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
  #         with:
  #           tag_name: ${{ github.ref }}
  #           release_name: Release ${{ github.ref }}
  #           body: |
  #             Automatic release
  #           draft: false
  #           prerelease: true
